version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: lab_postgres
    restart: always
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: lab_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: lab_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: student
      DB_PASSWORD: student
      DB_NAME: lab_db

volumes:
  postgres_data:
